[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.6.2"
aws-sdk-sqs = "1.67.0"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
